version: '3.1'
services:
  elasticsearch:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=erenadiguzel
      - RABBITMQ_DEFAULT_PASS=123456